stations = [
    'Naukova', 'Derzhprom', 'Universytet', 'Architektora Beketova', 
    'Zakhysnykiv Ukrayiny', 'Sportyvna', 'Malysheva', 'Metrobudivnykiv',
    'Gagarina', 'Maydan Konstytutsiyi', 'Tsentralniy Rinok', 'Pushkinska',
    'Istorychnyi Muzey'
]

connections = [
    ('Naukova', 'Derzhprom'),
    ('Derzhprom', 'Naukova'),
    ('Derzhprom', 'Universytet'),
    ('Universytet', 'Derzhprom'),
    ('Derzhprom',  'Architektora Beketova'),
    ('Architektora Beketova', 'Derzhprom'),
    ('Architektora Beketova', 'Zakhysnykiv Ukrayiny'),
    ('Zakhysnykiv Ukrayiny', 'Architektora Beketova'),
    ('Zakhysnykiv Ukrayiny', 'Metrobudivnykiv'),
    ('Metrobudivnykiv', 'Zakhysnykiv Ukrayiny'),
    ('Sportyvna', 'Malysheva'),
    ('Malysheva', 'Sportyvna'),
    ('Sportyvna', 'Metrobudivnykiv'),
    ('Metrobudivnykiv', 'Sportyvna'),
    ('Sportyvna', 'Gagarina'),
    ('Gagarina', 'Sportyvna'),
    ('Gagarina', 'Maydan Konstytutsiyi'),
    ('Maydan Konstytutsiyi', 'Gagarina'),
    ('Maydan Konstytutsiyi', 'Istorychnyi Muzey'),
    ('Istorychnyi Muzey', 'Maydan Konstytutsiyi'),
    ('Maydan Konstytutsiyi', 'Tsentralniy Rinok'),
    ('Tsentralniy Rinok', 'Maydan Konstytutsiyi'),
    ('Universytet', 'Istorychnyi Muzey'),
    ('Istorychnyi Muzey', 'Universytet'),
    ('Universytet', 'Pushkinska'),
    ('Pushkinska', 'Universytet'),
]

connections_weighted = [
    ('Naukova', 'Derzhprom', 2),
    ('Derzhprom', 'Naukova', 2),
    ('Derzhprom', 'Universytet', 1),
    ('Universytet', 'Derzhprom', 1),
    ('Derzhprom',  'Architektora Beketova', 3),
    ('Architektora Beketova', 'Derzhprom', 3),
    ('Architektora Beketova', 'Zakhysnykiv Ukrayiny', 3),
    ('Zakhysnykiv Ukrayiny', 'Architektora Beketova', 3),
    ('Zakhysnykiv Ukrayiny', 'Metrobudivnykiv', 2),
    ('Metrobudivnykiv', 'Zakhysnykiv Ukrayiny', 2),
    ('Sportyvna', 'Malysheva', 4),
    ('Malysheva', 'Sportyvna', 4),
    ('Sportyvna', 'Metrobudivnykiv', 1),
    ('Metrobudivnykiv', 'Sportyvna', 1),
    ('Sportyvna', 'Gagarina', 3),
    ('Gagarina', 'Sportyvna', 3),
    ('Gagarina', 'Maydan Konstytutsiyi', 4),
    ('Maydan Konstytutsiyi', 'Gagarina', 4),
    ('Maydan Konstytutsiyi', 'Istorychnyi Muzey', 1),
    ('Istorychnyi Muzey', 'Maydan Konstytutsiyi', 1),
    ('Maydan Konstytutsiyi', 'Tsentralniy Rinok', 2),
    ('Tsentralniy Rinok', 'Maydan Konstytutsiyi', 2),
    ('Universytet', 'Istorychnyi Muzey', 3),
    ('Istorychnyi Muzey', 'Universytet', 3),
    ('Universytet', 'Pushkinska', 4),
    ('Pushkinska', 'Universytet', 4),
]
